{
 "title": "Red Notices",
 "time": { "from": "1970-01-01T00:00:01.972Z", "to": "1970-01-01T00:00:02.025Z" },
 "panels": [
  {
   "title": "Red Notices",
   "type": "stat",
   "description": "Number of Red Notices",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM red_notice_details_entity_db"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sex_id, COUNT(sex_id) FROM red_notice_details_entity_db GROUP BY sex_id"
    }
   ]
  },
  {
   "title": "Country of birth",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT country_of_birth_id COUNTRY_OF_BIRTH FROM red_notice_details_entity_db"
    },
    {
     "rawSql": "SELECT id COUNTRY_OF_BIRTH, country_id FROM country"
    }
   ]
  },
  {
   "title": "Issuing country",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT issuing_country_id ISSUING_COUNTRY FROM arrest_warrant"
    },
    {
     "rawSql": "SELECT id ISSUING_COUNTRY, country_id FROM country"
    }
   ]
  },
  {
   "title": "Arrest Warrants Issued per Year",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT substring(entity_id from 0 for 5) TIME, count(substring(entity_id from 0 for 5)) FROM red_notice_details_entity_db\r\nGROUP BY substring(entity_id from 0 for 5)"
    }
   ]
  },
  {
   "title": "Arrest Warrants Issued per Year",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT substring(date_of_birth from 0 for 5) TIME, count(substring(date_of_birth from 0 for 5)) FROM red_notice_details_entity_db\r\nGROUP BY substring(date_of_birth from 0 for 5)"
    }
   ]
  },
  {
   "title": "Age",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT substring(date_of_birth from 0 for 5) time, count(substring(date_of_birth from 0 for 5)) FROM red_notice_details_entity_db\r\nGROUP BY substring(date_of_birth from 0 for 5)"
    }
   ]
  }
 ]
}