{
 "title": "Yellow Notices",
 "time": { "from": "1971-12-31T23:00:00.000Z", "to": "2026-01-01T22:59:59.000Z" },
 "panels": [
  {
   "title": "Yellow Notices",
   "type": "stat",
   "description": "Number of Yellow Notices",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM yellow_notice_details_entity_db"
    }
   ]
  },
  {
   "title": "Recorded per Year",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT array_agg(entity_id), substring(entity_id from 0 for 5) TIME, count(substring(entity_id from 0 for 5)) FROM yellow_notice_details_entity_db\r\nGROUP BY substring(entity_id from 0 for 5)"
    }
   ]
  },
  {
   "title": "Year of birth",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT array_agg(entity_id), substring(date_of_birth from 0 for 5) TIME, count(substring(date_of_birth from 0 for 5)) FROM yellow_notice_details_entity_db\r\nGROUP BY substring(date_of_birth from 0 for 5)"
    }
   ]
  },
  {
   "title": "Age at event",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT array_agg(entity_id), substring(date_of_birth from 0 for 5) time, substring(date_of_event from 0 for 5) time_event, count(substring(date_of_birth from 0 for 5)) FROM yellow_notice_details_entity_db\r\nGROUP BY substring(date_of_birth from 0 for 5), substring(date_of_event from 0 for 5)"
    }
   ]
  },
  {
   "title": "Country of birth",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  entity_id, country COUNTRY_OF_BIRTH\r\nFROM\r\n  yellow_notice_details_entity_db"
    },
    {
     "rawSql": "SELECT id COUNTRY_OF_BIRTH, country_id FROM country"
    }
   ]
  },
  {
   "title": "Sex",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sex_id, COUNT(sex_id) FROM yellow_notice_details_entity_db GROUP BY sex_id"
    }
   ]
  },
  {
   "title": "Height",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT array_agg(entity_id), height, COUNT(*) FROM yellow_notice_details_entity_db GROUP BY height"
    }
   ]
  }
 ]
}